name: "Execução Manual"

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Executar testes E2E (end-to-end)
        run: npm run cypress:run

      - name: Publicar relatórios
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: cypress/reports
