name: Execução Manual

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # ou a versão que você está usando

      - name: Instalar dependências
        run: |
          npm install
          npx cypress-mochawesome-reporter install

      - name: Executar Cypress
        run: npx cypress run
